@include_layout('header')

<body class="bg-light text-dark">
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-12">
                <h1 class="text-center">404</h1>
                <h1 class="text-center">Página não encontrada</h1>
                <div class="text-center">
                    <a href="/"><button class="btn btn-primary">Voltar</button></a>
                </div>
            </div>
        </div>
    </div>
</body>

</html>