@include_layout('header')

<div class="container">
    <h1>Editar Produto</h1>
    <form action="/produtos/update/{{ $produto->getId() }}" method="post">
        <div class="mb-3">
            <label for="produto" class="form-label">Produto</label>
            <input type="text" class="form-control" id="produto" name="produto" value="{{ $produto->getProduto() }}">
        </div>
        <div class="mb-3">
            <label for="descricao" class="form-label">Descrição</label>
            <input type="text" class="form-control" id="descricao" name="descricao" value="{{ $produto->getDescricao() }}">
        </div>
        <div class="mb-3">
            <label for="tipoProduto" class="form-label">Tipo do Produto</label>
            <select name="tipoProduto" id="tipoProduto" class="form-control">
                @foreach ($tiposProdutos as $tipoProduto)
                    <option value="{{ $tipoProduto }}" {{ $produto->getStringTipoProduto() == $tipoProduto ? 'selected' : '' }}>{{ $tipoProduto }}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="quantidade" class="form-label">Quantidade</label>
            <input type="text" class="form-control" id="quantidade" name="quantidade" value="{{ $produto->getQuantidade() }}">
        </div>
        <div class="mb-3">
            <label for="valor" class="form-label">Valor</label>
            <input type="text" class="form-control" id="valor" name="valor" value="{{ $produto->getValor() }}">
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>

@include_layout('footer')