@include_layout('header')


<div class="container">
    <!-- Cabeçalho -->
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Produtos</h1>
        <div class="btn-toolbar mb-2 mb-md-0 gap-3">
            <a class="btn btn-success" href="/produtos/criar">Adicionar Produto</a>
            <a href="/" class="btn btn-outline-secondary">Voltar</a>
        </div>
    </div>
    
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>Id.:</th>
                    <th>Produto</th>
                    <th>Descrição</th>
                    <th>Tipo do Produto</th>
                    <th>Quantidade</th>
                    <th>Valor</th>
                    <th>*</th>
                </tr>
            </thead>
            <tbody>
                @foreach($produtos as $produto)
                    <tr>
                        <td>{{ $produto->getId() }}</td>
                        <td>{{ $produto->getProduto() }}</td>
                        <td>{{ $produto->getDescricao() }}</td>
                        <td>{{ $produto->getStringTipoProduto() }}</td>
                        <td>{{ $produto->getQuantidade() }}</td>
                        <td>R$ {{ number_format($produto->getValor(), 2, ',', '.') }}</td>
                        <td>
                            <button class="btn btn-primary"><a style="color: white; text-decoration: none;" href="/produtos/editar/{{ $produto->getId() }}">Editar</a></button>
                            <button class="btn btn-danger"><a style="color: white; text-decoration: none;" href="/produtos/excluir/{{ $produto->getId() }}">Excluir</a></button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@include_layout('footer')