@include_layout('header')

<div class="container">
    <h1>Novo Cliente</h1>
    <form action="/funcionarios/update/{{ $funcionario->getId() }}" method="post">
        <div class="mb-3">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" value="{{ $funcionario->getNome() }}">
        </div>
        <div class="mb-3">
            <label for="idade" class="form-label">Idade</label>
            <input type="number" class="form-control" id="idade" name="idade" value="{{ $funcionario->getIdade() }}">
        </div>
        <div class="mb-3">
            <label for="cargo" class="form-label">Cargo</label>
            <select name="cargo" id="cargo" class="form-control">
                @foreach ($cargos as $cargo)
                   <option
                        @if ( $funcionario->getStringCargo() == $cargo )
                            selected
                        @endif
                        value="{{ $cargo }}"
                        >{{ $cargo }}</option>
                @endforeach
            </select>
        </div>
        <div class="mb-3">
            <label for="salario" class="form-label">Salario</label>
            <input type="text" class="form-control" id="salario" name="salario" value="{{ $funcionario->getSalario() }}">
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>

@include_layout('footer')